import Head from "next/head";
import Image from "next/image";
import Profile from "../compnents/Profile";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Profile />
    </div>
  );
}
